security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    user@example.com:
                        password: '$2y$10$z3RNfdGwR53SQOb520px4OCtgfUs/MhC27U8WrkET8CvtwFndH3Ea'

                        roles: ['ROLE_USER']

    firewalls:
        #dev:
         #   pattern: ^/(_(profiler|wdt)|css|images|js)/
          #  security: false

        main:
            pattern: ^/
            provider: in_memory
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /

            logout:
                path: app_logout
                target: app_login
            anonymous: true

    access_control:
        - { path: ^/products, roles: ROLE_USER }