version: '3.8'

services:
  app:
    image: php:7.4-fpm
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1 
