#index:
#    path: /
#    controller: App\Controller\DefaultController::index



product_list:
  path: /
  controller: App\Controller\ProductController::list

product_show:
  path: /products/{index}
  controller: App\Controller\ProductController::show
  requirements:
    index: '\d+'