#index:
#    path: /
#    controller: App\Controller\DefaultController::index



product_list:
  path: /
  controller: App\Controller\ProductController::list

product_show:
  path: /products/{index}
  controller: App\Controller\ProductController::show
  requirements:
    index: '\d+'

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout